members/urls.py
from django.conf.urls.defaults import patterns, url
from views import index, new, edit, delete, show, change_password, topup, search, result
urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^new/$', new),
    url(r'^search/$', search),
    url(r'^result/$', result),
    url(r'^(\d+)/edit/$', edit),
    url(r'^(\d+)/delete/$', delete),
    url(r'^(\d+)/show/$', show),
    url(r'^(\d+)/change/$', change_password),
    url(r'^(\d+)/topup/$', topup),
)

topups/urls.py
from django.conf.urls.defaults import patterns, url
from views import index, delete, show, new
urlpatterns = patterns('',
    url(r'^$', index),
    url(r'^(\d+)/delete/$', delete),
    url(r'^(\d+)/show/$', show),
    url(r'^(\d+)/new/$', new),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'manage.views.home'),
    url(r'^login/$', login),
    url(r'^logout/$', logout),
    url(r'^register/$', 'registrations.views.register'),
    url(r'^reactivate/$', 'registrations.views.reactivate'), 
    url(r'^confirm/(\w{30})/$', 'registrations.views.confirm'),
    url(r'^books/', include('books.urls')),
    url(r'^topups/', include('topups.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^purchases/', include('purchases.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^histories/', include('histories.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
)

members/models.py
# -*- coding: utf-8 -*-
from django.db import models
from groups.models import Group

def topup_point(amount):
    return int(amount / 2)

class Member(models.Model):
    GENDER_CHOICES = (
        ('M', u'男'),
        ('F', u'女'),
    )
    GENDER_CHOICES_WITH_EMPTY = (
        ('', u'不限'),
        ('M', u'男'),
        ('F', u'女'),
    )
    name = models.CharField(max_length=200)
    password = models.CharField(max_length=128)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birthday = models.DateField()
    valid_to = models.DateField()
    valid = models.BooleanField()
    identify_number = models.CharField(max_length=18)
    point = models.IntegerField(default=0)
    balance = models.FloatField(default=0)
    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.SET_NULL, related_name = 'members')
    create_at = models.DateTimeField(auto_now_add=True, null=False)
    update_at = models.DateTimeField(auto_now=True, null=False)
    def __unicode__(self):
        return u'%s<%s>' % (self.name, self.gender)
    def get_absolute_url(self):
        return "/members/%i/show/" % self.id
    def set_password(self, raw_password):#使用sha1算法加密密码串
        import random
        from django.contrib.auth.models import get_hexdigest
        algo = 'sha1'
        salt = get_hexdigest(algo, str(random.random()), str(random.random()))[:5]
        hsh = get_hexdigest(algo, salt, raw_password)
        self.password = '%s$%s$%s' % (algo, salt, hsh)
        self.save()
    def check_password(self, raw_password):#检查密码是否匹配
        from django.contrib.auth.models import check_password
        return check_password(raw_password, self.password)
    def topup(self, amount):#为此会员充值
        from topups.models import Topup
        topup = Topup()
        topup.member = self
        topup.amount = amount
        topup.save()
        self.balance += amount
        self.point += topup_point(amount)
        self.save()
    class Meta:
        ordering = ['-create_at']#指定默认排序方式为按时间降序
        

topups/models.py
# -*- coding: utf-8 -*-
from django.db import models
from members.models import Member

class Topup(models.Model):
    member = models.ForeignKey(Member, related_name='topups')
    amount = models.FloatField()
    create_at = models.DateTimeField(auto_now_add=True, null=False)
    update_at = models.DateTimeField(auto_now=True, null=False)
    def __unicode__(self):
        s = '%s - %.2f' % (self.member.name, self.amount)
        return s
    #def get_absolute_url(self):
    #    return "/topups/%i/show/" % self.id
    def new(self):#新充值时更新会员余额与积分
        m = self.member
        m.balance += self.amount
        m.point += int(self.amount / 2)
        m.save()
    class Meta:
        ordering = ['-create_at']#指定充值记录的默认排序方式为按时间降序

members/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from models import Member
from groups.models import Group
from helper import helper
from histories.models import History

class MemberForm(forms.ModelForm):#添加新会员的表单结构
    name = forms.CharField(max_length=200, label=u'姓名')
    password = forms.CharField(max_length=16, label=u'密码', widget=forms.PasswordInput)
    gender = forms.ChoiceField(choices=Member.GENDER_CHOICES, label=u'性别')
    birthday = forms.DateField(widget=forms.DateInput, label=u'生日')
    valid_to = forms.DateField(widget=forms.DateInput, label=u'有效期至')
    valid = forms.BooleanField(required=False, widget=forms.CheckboxInput, label=u'是否有效')
    identify_number = forms.RegexField(regex='^[0-9]{18}$', label=u'身份证')
    group = forms.ModelChoiceField(required=False, queryset=Group.objects.all(), label=u'会员组')
    def save(self):
        super(MemberForm, self).save()  
        d = self.cleaned_data
        m = self.instance
        m.set_password(d['password'])
        m.save()
        return m
    class Meta:
        model = Member
        exclude = ('password', 'balance', 'point', 'create_at', 'update_at')
        
class MemberEditForm(forms.ModelForm):#编辑会员的表单结构
    name = forms.CharField(max_length=200, label=u'姓名')
    password = forms.CharField(max_length=16, label=u'密码验证', widget=forms.PasswordInput)
    gender = forms.ChoiceField(choices=Member.GENDER_CHOICES, label=u'性别')
    birthday = forms.DateField(widget=forms.DateInput, label=u'生日')
    valid_to = forms.DateField(widget=forms.DateInput, label=u'有效期至')
    valid = forms.BooleanField(required=False, widget=forms.CheckboxInput, label=u'是否有效')
    identify_number = forms.RegexField(regex='^[0-9]{18}$', label=u'身份证')
    group = forms.ModelChoiceField(required=False, queryset=Group.objects.all(), label=u'会员组')
    def clean_password(self):
        d = self.cleaned_data
        m = self.instance
        if not m.check_password(d['password']):
            raise ValidationError(u'密码不正确')
        return d['password']
    class Meta:
        model = Member
        exclude = ('password', 'balance', 'point', 'create_at', 'update_at')
        
class MemberChangePasswordForm(forms.Form):#修改密码的表单结构
    password = forms.CharField(max_length=16, label=u'原密码', widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=16, label=u'新密码', widget=forms.PasswordInput)
    new_password_confirm = forms.CharField(max_length=16, label=u'新密码确认', widget=forms.PasswordInput)
    def __init__(self, instance, *args, **kwargs):
        self.instance = instance
        super(MemberChangePasswordForm, self).__init__(*args, **kwargs)
    def clean(self):
        d = self.cleaned_data
        m = self.instance
        if not m.check_password(d['password']):
            raise ValidationError(u'密码不正确')
        if (cmp(d['new_password'], d['new_password_confirm']) != 0):
            raise ValidationError(u'两次密码不一致')
        return d
    def save(self):        
        d = self.cleaned_data
        m = self.instance
        m.set_password(d['new_password'])
        m.save()
        return m
    
class MemberSearchForm(forms.Form):#搜索会员的表单结构
    id = forms.RegexField(required=False, regex='^[0-9]*$', label=u'编号')
    name = forms.CharField(required=False, max_length=200, label=u'姓名')
    gender = forms.TypedChoiceField(required=False, choices=Member.GENDER_CHOICES_WITH_EMPTY, label=u'性别')
    birthday = forms.DateField(required=False, widget=forms.DateInput, label=u'生日')
    identify_number = forms.CharField(required=False, max_length=18, label=u'身份证')
    
class MemberTopupForm(forms.Form):#充值的表单结构
    password = forms.CharField(max_length=16, label=u'密码', widget=forms.PasswordInput)
    amount = forms.FloatField(min_value=0, label=u'金额')
    def __init__(self, instance, *args, **kwargs):
        self.instance = instance
        super(MemberTopupForm, self).__init__(*args, **kwargs)
    def clean_password(self):
        p = self.cleaned_data['password']
        m = self.instance
        if not m.check_password(p):
            raise ValidationError(u'密码不正确')
        return p
    def save(self):        
        d = self.cleaned_data
        m = self.instance
        m.topup(d['amount'])
        m.save()
        return m

def add_history(user, content, topup, link):#记录与会员相关的事件
    if link:
        History(user=user, content=content, klass='Member', unicode=topup, url=topup.get_absolute_url()).save()
    else:
        History(user=user, content=content, klass='Member', unicode=topup).save()

def index(request):#会员列表
    members = Member.objects.all()
    return render_to_response('members/index.html', {'members':members, 'message': request.flash.get('message')}, context_instance=RequestContext(request))

@login_required
def new(request):#添加新会员
    form = MemberForm()
    if request.POST:
        form = MemberForm(request.POST)
        if form.is_valid():
            member = form.save()
            request.flash['message']=u'添加成功'
            add_history(request.user, u'添加会员', member, True)
            return redirect(member)
    return render_to_response('members/new.html', {'form':form}, context_instance=RequestContext(request))

@login_required
def edit(request, id):#编辑指定会员
    id = int(id)
    member = get_object_or_404(Member, pk=id)
    form = MemberEditForm(instance=member);
    if request.POST:
        form = MemberEditForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            request.flash['message']=u'保存成功'
            add_history(request.user, u'编辑会员', member, True)
            return redirect(member)
    return render_to_response('members/edit.html', {'form': form, 'id': id}, context_instance=RequestContext(request))

@login_required
def delete(request, id):#删除指定会员
    id = int(id)
    member = get_object_or_404(Member, pk=id)
    member.delete()
    request.flash['message']=u'删除成功'
    add_history(request.user, u'删除会员', member, False)
    return redirect(index)

@login_required
def show(request, id):#显示指定会员详细信息
    id = int(id)
    member = get_object_or_404(Member, pk=id)
    return render_to_response('members/show.html', {'member': member, 'message': request.flash.get('message')}, context_instance=RequestContext(request))

@login_required
def change_password(request, id):#更改密码
    id = int(id)
    member = get_object_or_404(Member, pk=id)
    form = MemberChangePasswordForm(member)
    if request.POST:
        form = MemberChangePasswordForm(member, request.POST)
        if form.is_valid():
            form.save()
            request.flash['message']=u'密码修改成功'
            History(user=request.user, content=u'修改会员#%d密码.' % member.id).save()
            return redirect(member)
    return render_to_response('members/change_password.html', {'form': form}, context_instance=RequestContext(request))

@login_required
def topup(request, id):#会员充值
    id = int(id)
    member = get_object_or_404(Member, pk=id)
    form = MemberTopupForm(member)
    if request.POST:
        form = MemberTopupForm(member, request.POST)
        if form.is_valid():
            form.save()
            request.flash['message']=u'充值成功'
            add_history(request.user, u'会员充值', member, False)
            return redirect(member)
    return render_to_response('members/topup.html', {'member': member,'form': form}, context_instance=RequestContext(request))

@login_required
def search(request):#搜索会员
    form = MemberSearchForm()
    if request.POST:
        form = MemberSearchForm(request.POST)
        if form.is_valid():
            d = {}
            for k, v in form.cleaned_data.iteritems():
                if v:
                    d[k] = v
            d['message'] = helper.get_search_message(form.fields, d)
            return redirect(helper.url_with_querystring(reverse(result), d))
    return render_to_response('members/search.html', {'form':form}, context_instance=RequestContext(request))

@login_required
def result(request):#执行会员搜索
    params = ''
    fields = MemberSearchForm().fields
    for k in request.GET:
        if k in fields:
            params += '%s__contains="%s",' % (k, request.GET[k])
    query = 'Member.objects.filter(' + params +')'
    members = eval(query)
    return render_to_response('members/result.html', {'members':members, 'message':request.GET.get('message')}, context_instance=RequestContext(request))

topups/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from models import Topup
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from members.models import Member
from histories.models import History

class TopupForm(forms.Form):#新充值记录的表单结构
    member = forms.ModelChoiceField(queryset=Member.objects.all(), label=u'会员组')
    password = forms.CharField(max_length=16, label=u'密码', widget=forms.PasswordInput)
    amount = forms.FloatField(min_value=0, label=u'金额')
    def __init__(self, instance, *args, **kwargs):
        self.instance = instance
        super(TopupForm, self).__init__(*args, **kwargs)
    def clean(self):
        d = self.cleaned_data
        p = d['password']
        m = d['member']
        if not m.check_password(p):
            raise ValidationError(u'密码不正确')
        return self.cleaned_data
    def save(self):        
        d = self.cleaned_data
        m = d['member']
        m.topup(d['amount'])
        m.save()
        return self

def add_history(user, content, topup, link):#记录充值相关操作
    if link:
        History(user=user, content=content, klass='Topup', unicode=topup, url=topup.get_absolute_url()).save()
    else:
        History(user=user, content=content, klass='Topup', unicode=topup).save()

def index(request):#充值记录列表
    topups = Topup.objects.all()
    return render_to_response('topups/index.html', {'topups': topups, 'message': request.flash.get('message')}, context_instance=RequestContext(request))

@login_required
def new(request):#添加新充值记录
    form = TopupForm()
    if request.POST:
        form = TopupForm(request.POST)
        if form.is_valid():
            topup = form.save()
            request.flash['message']=u'添加成功'
            add_history(request.user, u'添加充值记录', topup, True)
            return redirect(topup)
    return render_to_response('topups/new.html', {'form':form}, context_instance=RequestContext(request))

@login_required
def delete(request, id):#删除指定充值记录
    id = int(id)
    topup = get_object_or_404(Topup, pk=id)
    topup.delete()
    request.flash['message']=u'删除成功'
    add_history(request.user, u'删除充值记录', topup, False)
    return redirect(index)

@login_required
def show(request, id):#显示指定充值记录详细信息
    id = int(id)
    topup = get_object_or_404(Topup, pk=id)    
    return render_to_response('topups/show.html', {'topup': topup, 'message': request.flash.get('message')}, context_instance=RequestContext(request))

templates/members/change_password.html
{% extends "layout/two_col.html" %}
{% load helper %}
{% block title %}更改会员密码{% endblock %}
{% block nav %}
	<a href="../../../">首页</a>&gt;
	<a href="../../">会员列表</a>&gt;
	<a href="#">更改会员密码</a>
{% endblock %}
{% block main %}
	<h1>更改会员密码</h1>
	{% url members.views.change_password id as u%}
	<form id="member_change_password_form" action="{{u}}" method="post">
		{{ form.non_field_errors }}
	    {% for field in form %}
	        <div class="member-form-item">
	            {{ field.errors }}
	            {{ field.label_tag }}
	            {{ field }}
	        </div>
	    {% endfor %}
	    {% div_submit "确定" %}
	</form>
{% endblock %}

templates/members/edit.html
{% extends "layout/two_col.html" %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("input#id_birthday").datepicker();
			$("input#id_valid_to").datepicker();
		});
	</script>
{% endblock %}{% load helper %}
{% block title %}编辑会员{% endblock %}
{% block nav %}
	<a href="../../../">首页</a>&gt;
	<a href="../../">会员列表</a>&gt;
	<a href="#">编辑会员</a>
{% endblock %}
{% block main %}
	<h1>编辑会员</h1>
	{% url members.views.edit id as u%}
	<form id="edit_member_form" action="{{u}}" method="post">
		{{ form.non_field_errors }}
	    {% for field in form %}
	        <div class="member-form-item">
	            {{ field.errors }}
	            {{ field.label_tag }}
	            {{ field }}
	        </div>
	    {% endfor %}
	    {% div_submit "保存" %}
	</form>
{% endblock %}

templates/members/index.html
{% extends "layout/two_col.html" %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("div.delete a").click(function(event){
				if (confirm("你确定要删除此会员?"))
					return true;
				else
					return false;
			});
		});
	</script>
{% endblock %}
{% load helper %}
{% load pagination_tags %}
{% block title %}会员列表{% endblock %}
{% block nav %}
	<a href="../">首页</a>&gt;
	<a href="#">会员列表</a>
{% endblock %}
{% block main %}
	{% if message %}
	<ul class="messagelist">
		<li>{{message}}</li>
	</ul>
	{% endif %}
	<h1>会员列表</h1>
	{% url members.views.new as u %}
	{% div_link u "添加会员" "" "add link"%}
	{% url members.views.search as u %}
	{% div_link u "查找会员" "" "search link"%}
	{% autopaginate members 10 %}
	<table cellspacing="0">
		<thead>
			<tr>
				<th>编号</th>
				<th>姓名</th>
				<th>性别</th>
				<th>生日</th>
				<th>是否有效</th>
				<th>有效期至</th>
				<th>身份证</th>
				<th>积分</th>
				<th>余额</th>
				<th>会员组</th>
			</tr>
		</thead>
		<tbody>
			{% for member in members %}
				<tr>
					<th>{{member.id}}</th>
					<th>{{member.name}}</th>
					<th>{{member.get_gender_display}}</th>
					<th>{{member.birthday}}</th>
					<th>{{member.valid}}</th>
					<th>{{member.valid_to}}</th>
					<th>{{member.identify_number}}</th>
					<th>{{member.point}}</th>
					<th>{{member.balance}}</th>
					<th>{{member.group}}</th>
					<th>
						{%url members.views.show member.id as u%}
						{%div_link u "查看" "" "show link"%}
					</th>
					<th>
						{%url members.views.topup member.id as u%}
						{%div_link u "充值" "" "edit link"%}
					</th>
					<th>
						{%url members.views.edit member.id as u%}
						{%div_link u "编辑" "" "edit link"%}
					</th>
					<th>
						{%url members.views.delete member.id as u%}
						{%div_link u "删除" "" "delete link"%}
					</th>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% paginate %}
{% endblock %}

templates/members/new.html
{% extends "layout/two_col.html" %}
{% load helper %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("input#id_birthday").datepicker();
			$("input#id_valid_to").datepicker();
		});
	</script>
{% endblock %}
{% block title %}添加会员{% endblock %}
{% block nav %}
	<a href="../../">首页</a>&gt;
	<a href="../">会员列表</a>&gt;
	<a href="#">添加会员</a>
{% endblock %}
{% block main %}
	<h1>添加会员</h1>
	<form id="new_member_form" action="" method="post">
		{{ form.non_field_errors }}
	    {% for field in form %}
	        <div class="member-form-item">
	            {{ field.errors }}
	            {{ field.label_tag }}
	            {{ field }}
	        </div>
	    {% endfor %}
	    {% div_submit "添加" %}
	</form>
{% endblock %}

templates/members/result.html
{% extends "layout/two_col.html" %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("div.delete a").click(function(event){
				if (confirm("你确定要删除此会员?"))
					return true;
				else
					return false;
			});
		});
	</script>
{% endblock %}
{% load helper %}
{% load pagination_tags %}
{% block title %}查找结果{% endblock %}
{% block nav %}
	<a href="../../">首页</a>&gt;
	<a href="../">会员列表</a>&gt;
	<a href="#">查找结果</a>
{% endblock %}
{% block main %}
	<h1>查找结果{%if message%}({{message}}){%endif%}</h1>
	{% autopaginate members 10 %}
	<table cellspacing="0">
		<thead>
			<tr>
				<th>编号</th>
				<th>姓名</th>
				<th>性别</th>
				<th>生日</th>
				<th>是否有效</th>
				<th>有效期至</th>
				<th>身份证</th>
				<th>积分</th>
				<th>余额</th>
				<th>会员组</th>
			</tr>
		</thead>
		<tbody>
			{% for member in members %}
				<tr>
					<th>{{member.id}}</th>
					<th>{{member.name}}</th>
					<th>{{member.get_gender_display}}</th>
					<th>{{member.birthday}}</th>
					<th>{{member.valid}}</th>
					<th>{{member.valid_to}}</th>
					<th>{{member.identify_number}}</th>
					<th>{{member.point}}</th>
					<th>{{member.balance}}</th>
					<th>{{member.group}}</th>
					<th>
						{%url members.views.show member.id as u%}
						{%div_link u "查看" "" "show link"%}
					</th>
					<th>
						{%url members.views.topup member.id as u%}
						{%div_link u "充值" "" "edit link"%}
					</th>
					<th>
						{%url members.views.edit member.id as u%}
						{%div_link u "编辑" "" "edit link"%}
					</th>
					<th>
						{%url members.views.delete member.id as u%}
						{%div_link u "删除" "" "delete link"%}
					</th>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% paginate %}
{% endblock %}

templates/members/search.html
{% extends "layout/two_col.html" %}
{% load helper %}
{% block title %}查找会员{% endblock %}
{% block nav %}
	<a href="../../">首页</a>&gt;
	<a href="../">会员列表</a>&gt;
	<a href="#">查找会员</a>
{% endblock %}
{% block main %}
	<h1>查找会员</h1>
	<form id="search_member_form" action="" method="post">
		{{ form.non_field_errors }}
	    {% for field in form %}
	        <div class="member-form-item">
	            {{ field.errors }}
	            {{ field.label_tag }}
	            {{ field }}
	        </div>
	    {% endfor %}
	    {% div_submit "查找" %}
	</form>
{% endblock %}

templates/members/show.html
{% extends "layout/two_col.html" %}
{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("div.delete a").click(function(event){
				if (confirm("真的要删除此会员?"))
					return true;
				else
					return false;
			});
		});
	</script>
{% endblock %}
{% load helper %}
{% block title %}查看会员{% endblock %}
{% block nav %}
	<a href="../../../">首页</a>&gt;
	<a href="../../">会员列表</a>&gt;
	<a href="#">查看会员</a>
{% endblock %}
{% block main %}
	{% if message %}
	<ul class="messagelist">
		<li>{{message}}</li>
	</ul>
	{% endif %}
	<h1>查看会员</h1>
	{%url members.views.edit member.id as u%}
	{%div_link u "编辑" "" "edit link"%}
	{%url members.views.delete member.id as u%}
	{%div_link u "删除" "" "delete link"%}
	{% div_label_text member.id "id_id" "item" "编号" %}
	{% div_label_text member.name "id_name" "item" "姓名" %}
	{% div_label_text member.get_gender_display "id_gender" "item" "性别" %}
	{% div_label_text member.birthday "id_birthday" "item" "生日" %}
	{% div_label_text member.valid "id_valid" "item" "有效" %}
	{% div_label_text member.valid_to "id_valid_to" "item" "有效期至" %}	
	{% div_label_text member.identify_number "id_idnumber" "item" "身份证" %}
	{% div_label_text member.point "id_point" "item" "积分" %}
	{% div_label_text member.balance "id_balance" "item" "余额" %}
	{% div_label_text member.group "id_group" "item" "会员组" %}
	{% div_label_text member.create_at "id_create_at" "item" "创建时间" %}
	{% div_label_text member.update_at "id_update_at" "item" "更新时间" %}
{% endblock %}

templates/members/topup.html
{% extends "layout/two_col.html" %}
{% load helper %}
{% block title %}会员充值{% endblock %}
{% block nav %}
	<a href="../../../">首页</a>&gt;
	<a href="../../">会员列表</a>&gt;
	<a href="#">会员充值</a>
{% endblock %}
{% block main %}
	<h1>会员充值</h1>
	{% div_label_text member.id "id_id" "item" "编号" %}
	{% div_label_text member.name "id_name" "item" "姓名" %}
	{% url members.views.topup id as u%}
	<form id="member_topup_form" action="{{u}}" method="post">
		{{ form.non_field_errors }}
	    {% for field in form %}
	        <div class="member-form-item">
	            {{ field.errors }}
	            {{ field.label_tag }}
	            {{ field }}
	        </div>
	    {% endfor %}
	    {% div_submit "确定" %}
	</form>
{% endblock %}